workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build release APK (universal)
        script: flutter build apk --release --no-shrink --target-platform android-arm64
    artifacts:
      - build/**/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com  # ← غيّر هذا إلى بريدك الحقيقي
